// seconds
export const MILLISECONDS_IN_SECOND = 1000;

// minutes
export const SECONDS_IN_MINUTE = 60;
export const MILLISECONDS_IN_MINUTE =
  SECONDS_IN_MINUTE * MILLISECONDS_IN_SECOND;

// hours
export const MINUTES_IN_HOUR = 60;
export const SECONDS_IN_HOUR = MINUTES_IN_HOUR * SECONDS_IN_MINUTE;
export const MILLISECONDS_IN_HOUR = SECONDS_IN_HOUR * MILLISECONDS_IN_SECOND;

// days
export const HOURS_IN_DAY = 24;
export const MINUTES_IN_DAY = HOURS_IN_DAY * MINUTES_IN_HOUR;
export const SECONDS_IN_DAY = MINUTES_IN_DAY * SECONDS_IN_MINUTE;
export const MILLISECONDS_IN_DAY = SECONDS_IN_DAY * MILLISECONDS_IN_SECOND;

// weeks
export const DAYS_IN_WEEK = 7;
export const HOURS_IN_WEEK = DAYS_IN_WEEK * HOURS_IN_DAY;
export const MINUTES_IN_WEEK = HOURS_IN_WEEK * MINUTES_IN_HOUR;
export const SECONDS_IN_WEEK = MINUTES_IN_WEEK * SECONDS_IN_MINUTE;
export const MILLISECONDS_IN_WEEK = SECONDS_IN_WEEK * MILLISECONDS_IN_SECOND;
