export enum AppScreens {
  LOGIN = "/login",
  SIGN_UP = "/sign-up",
  FORGOT_PASSWORD = "/forgot-password",
  HOME = "/(drawer)/(tabs)",
  MEDICINES = "/(drawer)/(tabs)/medicines",
  MEDICINES_NEW = "/medicines/new",
  MEDICINES_SINGLE = "/medicines/[medicineId]",
  MEDICINES_EDIT = "/medicines/[medicineId]/edit",
  HEALTH_TRACKERS = "/(drawer)/(tabs)/health-trackers",
  HEALTH_TRACKERS_NEW = "/health-trackers/new",
  HEALTH_TRACKERS_SINGLE = "/health-trackers/[healthTrackerId]",
  HEALTH_TRACKERS_EDIT = "/health-trackers/[healthTrackerId]/edit",
  PROFILE = "/(drawer)/profile",
}
