#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged

# Disabling typecheck for now because
# there're type errors failing from inside of the `toastify-react-native` lib
# the project's type rules are stricter than in the lib

# and the `tsc` doesn't allow to somehow exclude node_modules from typechecking

# npm run typecheck
